In [2]:
import pandas as pd 
from io import StringIO
# data = '{"emp_name" : "ron" , "email" : "email@gmail.com " , "job" : "ML"}'
data = '{"emp_name" : ["ron" , "john" , "smith"] , "email" : ["ron@email" , "john@email" , "smith@email"] , "job" : ["ML" , "DL" , "NLP"]}'
df = pd.read_json(StringIO(data))

In [3]:
df

  emp_name        email  job
0      ron    ron@email   ML
1     john   john@email   DL
2    smith  smith@email  NLP

In [ ]:
# converting the abouvrt datafram agoin into the json 
df.to_json() # by defualt it make use of the indexx 
# in output we can see that "0 : ron " ") " 0 : email "" etc

'{"emp_name":{"0":"ron","1":"john","2":"smith"},"email":{"0":"ron@email","1":"john@email","2":"smith@email"},"job":{"0":"ML","1":"DL","2":"NLP"}}'

In [7]:
df.to_json(orient = 'index')

'{"0":{"emp_name":"ron","email":"ron@email","job":"ML"},"1":{"emp_name":"john","email":"john@email","job":"DL"},"2":{"emp_name":"smith","email":"smith@email","job":"NLP"}}'

In [ ]:
df.to_json(orient = 'records') # showsas the normal form

'[{"emp_name":"ron","email":"ron@email","job":"ML"},{"emp_name":"john","email":"john@email","job":"DL"},{"emp_name":"smith","email":"smith@email","job":"NLP"}]'

In [ ]:
# how to read te dat from the url tha contain the dat in csv  foramt 
df = pd.read_csv("" , header  = None)

In [9]:
df

  emp_name        email  job
0      ron    ron@email   ML
1     john   john@email   DL
2    smith  smith@email  NLP

In [ ]:
df.to_csv('wine.csv')
# using this is used to transfer the content ans aslo saved in the "CSV " file

In [12]:
# readingthe dat fro html file 
! pip install lxml
! pip installl html5lib

Requirement already satisfied: lxml in d:\mldlnlp\myenv\lib\site-packages (6.0.2)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: unknown command "installl" - maybe you meant "install"

In [14]:
url="https://www.fdic.gov/bank-failures/failed-bank-list"

df = pd.read_html(url)

In [ ]:
df[0] # can be used to show the  table present on the html file

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
5,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
6,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
7,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
8,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
9,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
10,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
11,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
12,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
13,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
14,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
15,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
16,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
17,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
18,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
19,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
20,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
21,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
22,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
23,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524
24,Harvest Community Bank,Pennsville,New Jersey,34951,First-Citizens Bank & Trust Company,"January 13, 2017",10523

In [22]:
# "match" key word is usedto show the content ofthe table only witin thetable that contain that key word 
url= "https://en.wikipedia.org/wiki/Mobile_country_code"
df = pd.read_html(url, match ="country" , header = 0)[0]

HTTPError: HTTP Error 403: Forbidden

In [28]:
! pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
dfexcel = pd.read_excel('data.xlsx')

In [ ]:
# reading the pckle file
dfexcel.to_pickle('dfexcel')

In [36]:

# reading the pickle file 
pd.read_pickle('dfexcel')

   no.  Name
0    1   ron
1    2  john
2    3   mon